# Generated by Django 5.2.3 on 2025-07-31 08:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'В обработке'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('data_archive', models.FileField(upload_to='uploads/data_archives/')),
                ('excel_file', models.FileField(upload_to='uploads/excel_files/')),
            ],
        ),
    ]
